---
- name: Instalar Python 3.10
  apt:
    name:
      - python3.10
      - python3.10-venv
      - python3.10-distutils
    state: present

- name: Ajustar alternativa python3
  alternatives:
    name: python3
    path: /usr/bin/python3.10
