---
- name: Adicionar NodeSource repo
  shell: "curl -fsSL https://deb.nodesource.com/setup_{{ node_major }}.x | bash -"
  args:
    executable: /bin/bash

- name: Instalar Node.js
  apt:
    name: nodejs
    state: present

- name: Instalar PNPM global
  npm:
    name: "{{ pnpm_package }}"
    global: yes
